package scubase3;

/**
 *
 * @author liu1028, eden0021, mitc0341, craw0117, kris0068
 */
public class ScubaFrame extends javax.swing.JFrame {

    private final ScubaModel model;
    private final ScubaController controller;

    /**
     * Creates a new ScubaFrame and initializes all of the form components.
     *
     * @param controller the ScubaController
     */
    public ScubaFrame(ScubaController controller) {
        this.controller = controller;
        this.model = controller.getModel();
        initComponents();
    }

    /**
     * Provides external access to the controller object
     *
     * @return ScubaController
     */
    public ScubaController getController() {
        return controller;
    }

    /**
     * Updates dynamic state dependant components. Must be called after every
     * state change.
     */
    public void update() {
        sInputPanel.update();
        sOutputPanel.update();
        sTablePanel.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sVerticalSplitPane = new javax.swing.JSplitPane();
        sSplitPane = new javax.swing.JSplitPane();
        sOutputPanel = new scubase3.panels.ScubaOutputPanel();
        sInputPanel = new scubase3.panels.ScubaInputPanel();
        sTablePanel = new scubase3.panels.ScubaTablePanel();
        sMenuBar = new javax.swing.JMenuBar();
        sFileMenu = new javax.swing.JMenu();
        sFileSeparator2 = new javax.swing.JPopupMenu.Separator();
        sExitButton = new javax.swing.JMenuItem();
        sCalcMenu = new javax.swing.JMenu();
        sEADButton = new javax.swing.JMenuItem();
        sMODButton = new javax.swing.JMenuItem();
        sBMButton = new javax.swing.JMenuItem();
        sPPButton = new javax.swing.JMenuItem();
        sSMODButton = new javax.swing.JMenuItem();
        sTablesMenu = new javax.swing.JMenu();
        sEADTableButton = new javax.swing.JMenuItem();
        sPPTableButton = new javax.swing.JMenuItem();
        sHelpMenu = new javax.swing.JMenu();
        sHelpDocsButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dive Calculator Version 0.1 PRERELEASE");
        setMinimumSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        sVerticalSplitPane.setDividerSize(3);
        sVerticalSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        sSplitPane.setDividerSize(3);

        sOutputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sSplitPane.setRightComponent(sOutputPanel);

        sInputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sSplitPane.setLeftComponent(sInputPanel);

        sVerticalSplitPane.setLeftComponent(sSplitPane);

        sTablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sVerticalSplitPane.setRightComponent(sTablePanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(sVerticalSplitPane, gridBagConstraints);

        sFileMenu.setText("File");
        sFileMenu.add(sFileSeparator2);

        sExitButton.setText("Exit");
        sExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sExitButtonActionPerformed(evt);
            }
        });
        sFileMenu.add(sExitButton);

        sMenuBar.add(sFileMenu);

        sCalcMenu.setText("Calculate");

        sEADButton.setText("Equivalent Air Depth (EAD)");
        sEADButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEADButtonActionPerformed(evt);
            }
        });
        sCalcMenu.add(sEADButton);

        sMODButton.setText("Maximum Operating Depth (MOD)");
        sMODButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMODButtonActionPerformed(evt);
            }
        });
        sCalcMenu.add(sMODButton);

        sBMButton.setText("Best Mix (BM)");
        sBMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBMButtonActionPerformed(evt);
            }
        });
        sCalcMenu.add(sBMButton);

        sPPButton.setText("Partial Pressure (PP)");
        sPPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPPButtonActionPerformed(evt);
            }
        });
        sCalcMenu.add(sPPButton);

        sSMODButton.setText("Standard MOD (SMOD)");
        sSMODButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSMODButtonActionPerformed(evt);
            }
        });
        sCalcMenu.add(sSMODButton);

        sMenuBar.add(sCalcMenu);

        sTablesMenu.setText("Tables");

        sEADTableButton.setText("Equivalent Air Depth (EAD)");
        sEADTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEADTableButtonActionPerformed(evt);
            }
        });
        sTablesMenu.add(sEADTableButton);

        sPPTableButton.setText("Partial Pressure (PP)");
        sPPTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPPTableButtonActionPerformed(evt);
            }
        });
        sTablesMenu.add(sPPTableButton);

        sMenuBar.add(sTablesMenu);

        sHelpMenu.setText("Help");

        sHelpDocsButton.setText("User Manual");
        sHelpDocsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sHelpDocsButtonActionPerformed(evt);
            }
        });
        sHelpMenu.add(sHelpDocsButton);

        sMenuBar.add(sHelpMenu);

        setJMenuBar(sMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sExitButtonActionPerformed

    private void sEADTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEADTableButtonActionPerformed
        controller.setTableType(Const.CALCULATION_TYPE_EAD);
        this.sTablePanel.forceButtonUpdate();
    }//GEN-LAST:event_sEADTableButtonActionPerformed

    private void sPPTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPPTableButtonActionPerformed
        controller.setTableType(Const.CALCULATION_TYPE_PP);
        this.sTablePanel.forceButtonUpdate();
    }//GEN-LAST:event_sPPTableButtonActionPerformed

    private void sEADButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEADButtonActionPerformed
        controller.setCalcType(Const.CALCULATION_TYPE_EAD);
        this.sInputPanel.forceButtonUpdate();
    }//GEN-LAST:event_sEADButtonActionPerformed

    private void sMODButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMODButtonActionPerformed
        controller.setCalcType(Const.CALCULATION_TYPE_MOD);
        this.sInputPanel.forceButtonUpdate();
    }//GEN-LAST:event_sMODButtonActionPerformed

    private void sBMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBMButtonActionPerformed
        controller.setCalcType(Const.CALCULATION_TYPE_BM);
        this.sInputPanel.forceButtonUpdate();
    }//GEN-LAST:event_sBMButtonActionPerformed

    private void sPPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPPButtonActionPerformed
        controller.setCalcType(Const.CALCULATION_TYPE_PP);
        this.sInputPanel.forceButtonUpdate();
    }//GEN-LAST:event_sPPButtonActionPerformed

    private void sSMODButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSMODButtonActionPerformed
        controller.setCalcType(Const.CALCULATION_TYPE_SMOD);
        this.sInputPanel.forceButtonUpdate();
    }//GEN-LAST:event_sSMODButtonActionPerformed

    private void sHelpDocsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sHelpDocsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sHelpDocsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem sBMButton;
    private javax.swing.JMenu sCalcMenu;
    private javax.swing.JMenuItem sEADButton;
    private javax.swing.JMenuItem sEADTableButton;
    private javax.swing.JMenuItem sExitButton;
    private javax.swing.JMenu sFileMenu;
    private javax.swing.JPopupMenu.Separator sFileSeparator2;
    private javax.swing.JMenuItem sHelpDocsButton;
    private javax.swing.JMenu sHelpMenu;
    private scubase3.panels.ScubaInputPanel sInputPanel;
    private javax.swing.JMenuItem sMODButton;
    private javax.swing.JMenuBar sMenuBar;
    private scubase3.panels.ScubaOutputPanel sOutputPanel;
    private javax.swing.JMenuItem sPPButton;
    private javax.swing.JMenuItem sPPTableButton;
    private javax.swing.JMenuItem sSMODButton;
    private javax.swing.JSplitPane sSplitPane;
    private scubase3.panels.ScubaTablePanel sTablePanel;
    private javax.swing.JMenu sTablesMenu;
    private javax.swing.JSplitPane sVerticalSplitPane;
    // End of variables declaration//GEN-END:variables
}
