package scubase3.panels;

import scubase3.Const;
import scubase3.ScubaController;

/**
 *
 * @author liu1028, eden0021, mitc0341, craw0117, kris0068
 */
public class ScubaOutputPanel extends javax.swing.JPanel {

    private final ScubaController controller;

    /**
     * Creates new form ScubaOutputPanel
     *
     * @param controller
     */
    public ScubaOutputPanel(ScubaController controller) {
        this.controller = controller;
        initComponents();
    }

    public void update() {
        if (Const.UNSAFE_OUTPUT_VALUE.equals(controller.getOutputValue())) {
            outputText.setText(Const.UNSAFE_OUTPUT_MESSAGE);
        } else {
            if (Const.TYPE_BM.equals(controller.getCalculationType())) {
                outputText.setText(controller.getCalculationType() + ": " + controller.getOutputValue()
                        + controller.getOutputUnit());
            } else {
                outputText.setText(controller.getCalculationType() + ": " + controller.getOutputValue()
                        + controller.getOutputUnit() + ", Oxygen: " + controller.getOutputOxygen()
                        + Const.UNIT_PERCENT);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        outputLHS = new javax.swing.JPanel();
        outputOxygenDisplay = new javax.swing.JSlider();
        outputOxygenLabel = new javax.swing.JLabel();
        outputRHS = new javax.swing.JPanel();
        outputText = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.GridBagLayout());

        outputLHS.setPreferredSize(new java.awt.Dimension(150, 300));
        outputLHS.setLayout(new java.awt.GridBagLayout());

        outputOxygenDisplay.setOrientation(javax.swing.JSlider.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        outputLHS.add(outputOxygenDisplay, gridBagConstraints);

        outputOxygenLabel.setText("O2%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        outputLHS.add(outputOxygenLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.ipady = 240;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(outputLHS, gridBagConstraints);

        outputRHS.setPreferredSize(new java.awt.Dimension(150, 300));
        outputRHS.setLayout(new java.awt.GridBagLayout());

        outputText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputText.setText("[This is the output area]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        outputRHS.add(outputText, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 286;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(outputRHS, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel outputLHS;
    private javax.swing.JSlider outputOxygenDisplay;
    private javax.swing.JLabel outputOxygenLabel;
    private javax.swing.JPanel outputRHS;
    private javax.swing.JLabel outputText;
    // End of variables declaration//GEN-END:variables
}
