package scubase3.panels;

import javax.swing.JTable;
import scubase3.Const;
import scubase3.ScubaController;
import scubase3.ScubaSE3;

/**
 * ScubaTablePanel is the lower panel in the user interface
 *
 * @author liu1028, eden0021, mitc0341, craw0117, kris0068
 */
public class ScubaTablePanel extends javax.swing.JPanel {

    /**
     * Default constructor for ScubaTablePanel
     */
    public ScubaTablePanel() {
        initComponents();
    }

    /**
     * Gets the controller object using the static method in
     * <code>ScubaSE3</code>
     *
     * @return
     * @see ScubaSE3#getController()
     */
    public static ScubaController getController() {
        return ScubaSE3.getController();
    }

    /**
     * Updates dynamic components - must be called after state change.
     */
    public void update() {
        String tableType = getController().getTableType();
        switch (tableType) {
            case Const.TYPE_EAD:
                JTable tableEAD = getController().getEADTable();
                tableScollPane.setViewportView(tableEAD);
                eadTableSelect.setSelected(true);
                ppTableSelect.setSelected(false);
                break;
            case Const.TYPE_PP:
                JTable tablePP = getController().getPPTable();
                tableScollPane.setViewportView(tablePP);
                ppTableSelect.setSelected(true);
                eadTableSelect.setSelected(false);
                break;
            default:
                throw new java.lang.Error("Invalid tableType: " + tableType);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableButtonGroup = new javax.swing.ButtonGroup();
        inputToolBar = new javax.swing.JToolBar();
        eadTableSelect = new javax.swing.JToggleButton();
        ppTableSelect = new javax.swing.JToggleButton();
        tableScollPane = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JPanel();
        eadTable = new javax.swing.JPanel();
        ppTable = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        inputToolBar.setBorder(null);
        inputToolBar.setFloatable(false);
        inputToolBar.setRollover(true);

        tableButtonGroup.add(eadTableSelect);
        eadTableSelect.setSelected(true);
        eadTableSelect.setText("EAD");
        eadTableSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eadTableSelect.setFocusable(false);
        eadTableSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eadTableSelect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eadTableSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eadTableSelectActionPerformed(evt);
            }
        });
        inputToolBar.add(eadTableSelect);

        tableButtonGroup.add(ppTableSelect);
        ppTableSelect.setText("PP");
        ppTableSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ppTableSelect.setFocusable(false);
        ppTableSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ppTableSelect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ppTableSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppTableSelectActionPerformed(evt);
            }
        });
        inputToolBar.add(ppTableSelect);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(inputToolBar, gridBagConstraints);

        tableDisplay.setMinimumSize(new java.awt.Dimension(650, 0));
        tableDisplay.setPreferredSize(new java.awt.Dimension(500, 100));
        tableDisplay.setRequestFocusEnabled(false);
        tableDisplay.setLayout(new java.awt.GridBagLayout());

        eadTable.setMinimumSize(new java.awt.Dimension(500, 500));
        eadTable.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tableDisplay.add(eadTable, gridBagConstraints);

        ppTable.setMinimumSize(new java.awt.Dimension(500, 500));
        ppTable.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tableDisplay.add(ppTable, gridBagConstraints);

        tableScollPane.setViewportView(tableDisplay);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(tableScollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Called when the EAD button is selected from the button group
     *
     * @param evt
     */
    private void eadTableSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eadTableSelectActionPerformed
    {//GEN-HEADEREND:event_eadTableSelectActionPerformed
        getController().setTableType(Const.TYPE_EAD);
    }//GEN-LAST:event_eadTableSelectActionPerformed

    /**
     * Called when the PP button is selected from the button group
     *
     * @param evt
     */
    private void ppTableSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ppTableSelectActionPerformed
    {//GEN-HEADEREND:event_ppTableSelectActionPerformed
        getController().setTableType(Const.TYPE_PP);
    }//GEN-LAST:event_ppTableSelectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eadTable;
    private javax.swing.JToggleButton eadTableSelect;
    private javax.swing.JToolBar inputToolBar;
    private javax.swing.JPanel ppTable;
    private javax.swing.JToggleButton ppTableSelect;
    private javax.swing.ButtonGroup tableButtonGroup;
    private javax.swing.JPanel tableDisplay;
    private javax.swing.JScrollPane tableScollPane;
    // End of variables declaration//GEN-END:variables
}
